# Generated by Django 4.1 on 2022-09-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estadousuario",
            fields=[
                (
                    "id_estadousuario",
                    models.FloatField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "estadousuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("id_permiso", models.FloatField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=4000, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
            ],
            options={
                "db_table": "permiso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("id_sesion", models.FloatField(primary_key=True, serialize=False)),
                ("llave", models.CharField(blank=True, max_length=64, null=True)),
                ("expiracion", models.BigIntegerField(blank=True, null=True)),
                ("fechacreacion", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sesion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.FloatField(primary_key=True, serialize=False)),
                ("password", models.CharField(blank=True, max_length=80, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_usuario",
                    models.OneToOneField(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="identificacion.usuario",
                    ),
                ),
                (
                    "primernombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundonombre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primerapellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "segundoapellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=50, null=True)),
                ("telefono", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "db_table": "cliente",
                "managed": False,
            },
        ),
    ]
